# Generated by Django 4.1 on 2022-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedulee', '0002_project_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='cloth_model',
            field=models.CharField(choices=[('Kemeja', 'Kemeja'), ('Kaos', 'Kaos'), ('Celana', 'Celana'), ('Rok', 'Rok'), ('Sepatu', 'Sepatu'), ('Aksesoris', 'Aksesoris'), ('Lainnya', 'Lainnya')], default='Kemeja', max_length=30),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='material',
            field=models.CharField(choices=[('Katun', 'Katun'), ('Linen', 'Linen'), ('Denim', 'Denim'), ('Kulit', 'Kulit'), ('Polyester', 'Polyester'), ('Suede', 'Suede'), ('Sutra', 'Sutra'), ('Velvet', 'Velvet'), ('Rajut', 'Rajut'), ('Rayon', 'Rayon'), ('Jersey', 'Jersey'), ('Twistcone', 'Twistcone'), ('Lainnya', 'Lainnya')], default='Katun', max_length=30),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='type',
            field=models.CharField(choices=[('Perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki'), ('Anak perempuan', 'Anak perempuan'), ('Anak laki-laki', 'Anak laki-laki')], default='Perempuan', max_length=30),
        ),
    ]
