# Generated by Django 4.1 on 2022-10-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedulee', '0002_cloth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('link', models.CharField(max_length=256)),
                ('ammount', models.BigIntegerField()),
                ('akhir_waktu', models.DateField()),
            ],
        ),
    ]
