# Generated by Django 4.1 on 2022-11-02 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedulee', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='divisi',
            field=models.CharField(choices=[('Panitia Inti', 'Panitia Inti'), ('Kesehatan', 'Kesehatan'), ('Hubungan Masyarakat', 'Hubungan Masyarakat'), ('Tenaga Kerja', 'Tenaga Kerja')], default='Panitia Inti', max_length=255),
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('donasi', models.IntegerField()),
                ('sembako', models.CharField(choices=[('Select...', 'Select...'), ('Beras', 'Beras'), ('Garam', 'Garam'), ('Sirup', 'Sirup'), ('Gula', 'Gula'), ('Kopi', 'Kopi'), ('Minyak', 'Minyak'), ('Teh', 'Teh'), ('Lainnya', 'Lainnya')], default='Select...', max_length=30)),
                ('amount', models.BigIntegerField()),
                ('pmethod', models.CharField(choices=[('Select...', 'Select...'), ('Mandiri', 'Mandiri'), ('BNI', 'BNI'), ('BRI', 'BRI'), ('BCA', 'BCA')], default='Select...', max_length=30)),
                ('ccnumber', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
