# Generated by Django 4.1 on 2022-10-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedulee', '0004_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='divisi',
            field=models.CharField(choices=[('Logistics', 'Logistics'), ('Secretary', 'Secretary'), ('Worker', 'Worker')], default='Logistics', max_length=255),
        ),
    ]
