# Generated by Django 4.1 on 2022-11-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedulee', '0005_alter_volunteer_divisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('pnumber', models.CharField(max_length=256)),
                ('donation', models.CharField(max_length=1024)),
                ('message', models.CharField(max_length=1024)),
                ('pmethod', models.CharField(choices=[('Select...', 'Select...'), ('Mandiri', 'Mandiri'), ('BNI', 'BNI'), ('BRI', 'BRI'), ('BRI', 'BRI'), ('BCA', 'BCA'), ('Lainnya', 'Lainnya')], default='Select...', max_length=30)),
                ('hidename', models.BooleanField(default=False)),
                ('ccnumber', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='durasi',
        ),
    ]
