# Generated by Django 4.1 on 2022-11-02 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedulee', '0005_alter_volunteer_divisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('pnumber', models.IntegerField()),
                ('donation', models.CharField(max_length=1024)),
                ('message', models.CharField(max_length=1024)),
                ('pmethod', models.CharField(choices=[('Select...', 'Select...'), ('Mandiri', 'Mandiri'), ('BNI', 'BNI'), ('BRI', 'BRI'), ('BCA', 'BCA')], default='Select...', max_length=30)),
                ('ccnumber', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
