# Generated by Django 4.1 on 2022-11-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedulee', '0005_blood'),
        ('pedulee', '0005_money_date'),
    ]

    operations = [
    ]
