# Generated by Django 4.1 on 2022-12-01 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedulee', '0006_merge_0005_blood_0005_money_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 1, 15, 55, 6, 482074)),
        ),
    ]
