# Generated by Django 4.1 on 2022-12-01 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedulee', '0007_alter_money_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 1, 22, 26, 21, 528945)),
        ),
    ]
